version: '3.8'
services:
  spring:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8080
    depends_on:
      - mysql
    env_file:
      - .env
    links:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${USER}
      - MYSQL_DATABASE=${DATABASE}
      - MYSQL_ROOT_PASSWORD:${PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
