version: '3.8'
services:
  spring:
    image: ${DOCKER_REPOSITORY}/jjoing
    ports:
      - 80:8080
    depends_on:
      - s3
    env_file:
      - .env

  s3:
    image: minio/minio:latest
    environment:
      - MINIO_ACCESS_KEY=${S3_ACCESS_KEY}
      - MINIO_SECRET_KEY=${S3_SECRET_KEY}
    ports:
      - "9001:9000"
    command: server /data
    volumes:
      - s3data:/data

volumes:
  s3data: