version: '3.8'
services:
  spring:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8080
    depends_on:
      - mysql
      - s3
    env_file:
      - .env
    links:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${USER}
      - MYSQL_DATABASE=${DATABASE}
      - MYSQL_ROOT_PASSWORD:${PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql

  s3:
    image: minio/minio:latest
    environment:
      - MINIO_ACCESS_KEY=${S3_ACCESS_KEY}
      - MINIO_SECRET_KEY=${S3_SECRET_KEY}
    ports:
      - "9001:9000"
    command: server /data
    volumes:
      - s3data:/data

volumes:
  mysql_data:
  s3data: