spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url : ${URL}
    username: ${USER}
    password: ${PASSWORD}

  logging:
    level:
      org:
        hibernate:
          SQL: debug

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_SECRET_KEY}
            redirect-uri: ${GOOGLE_REDIRECT_URL}
            scope:
              - profile
              - email

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jackson:
    serialization:
      fail-on-empty-beans: false

auth:
  jwt:
    header: ${HEADER}
    secret: ${SECRET}
    accessExp: ${ACCESS-EXP}
    refreshExp: ${REFRESH-EXP}
    prefix: ${PREFIX}

cloud:
  aws:
    s3:
      bucket: ${BUCKET_NAME}
    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      instance-profile: true
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}

decorator:
  datasource:
    p6spy:
      enable-logging: true